// CutterDLL.idl: источник языка IDL для CutterDLL
//

// Этот файл будет обработан средством MIDL для
// создание библиотеки типов ($handlersafeidlname$.tlb) и кода маршалирования.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(0759412f-522d-4816-a5c4-b05d77b12b7d),
	version(1.0),
]
library CutterDLLLib
{
	importlib("stdole2.tlb");
};

